AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  Application for controlling the state of Minecraft game servers

Parameters:
  Environment:
    Type: String
    Description: Environment name will be appended to resource names
  FunctionRole:
    Type: String
    NoEcho: true
    Description: IAM role used in execution of Lambda functions
  EventBridgeRole:
    Type: String
    NoEcho: true
    Description: IAM role used in EventBridge rules
  StateMachineRole:
    Type: String
    NoEcho: true
    Description: IAM role used in StateMachine executions 
  ApiDomainName:
    Type: String
    NoEcho: true
    Description: Domain within an existing hosted zone for pretty URL configuration
  CertificateArn:
    Type: String
    NoEcho: true
    Description: ARN of an existing AWS managed certificate that supports the API domain
  HostedZoneId:
    Type: String
    NoEcho: true
    Description: Hosted Zone ID for the domain defined in 'ApiDomainName'

Outputs:
  IdleServerStateMachineARN:
    Value: !GetAtt IdleServerStateMachine.Arn

Conditions:
  IsMainConfig: !Equals [!Ref Environment, main]

Globals:
  Function:
    Runtime: python3.8
    Timeout: 10
    Tags:
      Application: minecraft
      Environment: !Ref Environment

Resources:
  # ---------------------------------------------
  #
  # State Machine definition
  #

  IdleServerSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub minecraft-${Environment}-idleserver-schedule
      State: !If [IsMainConfig, ENABLED, DISABLED]
      ScheduleExpression: 'rate(1 hour)'
      Targets:
        - Id: IdleServerStateMachine
          Arn: !Ref IdleServerStateMachine
          RoleArn: !Ref EventBridgeRole

  IdleServerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub minecraft-${Environment}-idle-servers
      Role: !Ref StateMachineRole
      DefinitionUri: statemachine/idle-servers.asl.json
      DefinitionSubstitutions:
        Environment: !Ref Environment
      Tags:
        Application: minecraft
        Environment: !Ref Environment


  # ---------------------------------------------
  #
  # API Gateway definition
  #

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Domain:
        DomainName: !Ref ApiDomainName
        CertificateArn: !Ref CertificateArn
        Route53:
          HostedZoneId: !Ref HostedZoneId
      StageName: !Ref Environment
      OpenApiVersion: 3.0.1
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          UsagePlanName: !Sub minecraft-${Environment}-usage-plan
          CreateUsagePlan: PER_API
          Throttle:
            RateLimit: 10
            BurstLimit: 10
          Quota:
            Limit: 1000
            Period: DAY
          Tags:
            - Key: Application
              Value: minecraft
            - Key: Environment
              Value: !Ref Environment
      MethodSettings:
        - HttpMethod: '*'
          ResourcePath: '/*'
          ThrottlingRateLimit: 10
          ThrottlingBurstLimit: 10
      Tags:
        Application: minecraft
        Environment: !Ref Environment

  # ---------------------------------------------
  #
  # /servers operations
  #

  GetServersOperation:
    Type: AWS::Serverless::Function
    DependsOn: GetServersOperationLogs
    Properties:
      FunctionName: !Sub minecraft-${Environment}-get-servers
      CodeUri: src/
      Handler: mcservers.get_handler
      Role: !Ref FunctionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /servers
            Method: get

  # https://github.com/aws/serverless-application-model/issues/851
  GetServersOperationLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/minecraft-${Environment}-get-servers
      RetentionInDays: 30

  # ---------------------------------------------
  #
  # /servers/{name} operations
  #

  GetServerOperation:
    Type: AWS::Serverless::Function
    DependsOn: GetServerOperationLogs
    Properties:
      FunctionName: !Sub minecraft-${Environment}-get-server
      CodeUri: src/
      Handler: mcserver.get_handler
      Role: !Ref FunctionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /servers/{name}
            Method: get

  # https://github.com/aws/serverless-application-model/issues/851
  GetServerOperationLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/minecraft-${Environment}-get-server
      RetentionInDays: 30

  PostServerOperation:
    Type: AWS::Serverless::Function
    DependsOn: PostServerOperationLogs
    Properties:
      FunctionName: !Sub minecraft-${Environment}-post-server
      CodeUri: src/
      Handler: mcserver.post_handler
      Role: !Ref FunctionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /servers/{name}
            Method: post

  # https://github.com/aws/serverless-application-model/issues/851
  PostServerOperationLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/minecraft-${Environment}-post-server
      RetentionInDays: 30

  # ---------------------------------------------
  #
  # /servers/{name}/users operations
  #

  GetUsersOperation:
    Type: AWS::Serverless::Function
    DependsOn: GetUsersOperationLogs
    Properties:
      FunctionName: !Sub minecraft-${Environment}-get-users
      CodeUri: src/
      Handler: mcusers.get_handler
      Role: !Ref FunctionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /servers/{name}/users
            Method: get

  # https://github.com/aws/serverless-application-model/issues/851
  GetUsersOperationLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/minecraft-${Environment}-get-users
      RetentionInDays: 30
